echo "We are trying this practical from linux EC2"
echo "I am from Young minds"
echo "We are from batch-27" 
echo "I am learning Git/Github"
echo "I have added new code"
echo "I am writing this on 08/09/2025"
echo "I am doing this fast"
echo "I am the best"
echo "I am agin adding another file here in new branch"
